# vis.js javascript build
# run 'watch -n 1 make'

vis_dir = src

vis_src =	${vis_dir}/namespace.js\
					${vis_dir}/defaults.js\
					${vis_dir}/app.js\

# vis.js build
vis.js: ${vis_src}
	cat > $@ $^
